#!/usr/bin/expect -f
#
# Send mldonkey a command
#
set timeout 10 

if $argc<1 {
  send_user "$argv0: Not enough parameters !!!\n"
  send_user "      : Usage $argv0 \"mldonkey_command\"\n"
  exit
}

set mlcmd $argv 
set user "admin"
set password "password"

spawn telnet 127.0.0.1 4000
expect -exact "\> "
send "auth $user $password\r"
expect -exact "\> "
send "\r\r"
sleep 1
expect -exact "\> "
send "$mlcmd\r"
expect -exact "\> "
send "q\r"
expect -exact "\$"
exit
